//! `Provenance` — end-to-end event traceability for the LUMYX pipeline.
//!
//! Every `LogicalFrame` carries a `Provenance` that records the causal chain
//! from the audio input to the final pixel output. This enables:
//!
//! - **Audit**: reconstruct exactly what caused a visual artifact.
//! - **Replay**: reproduce any frame from its provenance record.
//! - **Debug**: trace which effect / section / beat triggered what.
//! - **Regression**: compare provenance between runs to detect drift.
//!
//! ## Design
//!
//! Provenance is a **lightweight, append-only chain of events** — no allocation
//! on the hot path (the `FrameSource` enum is Copy-friendly for common cases).
//!
//! ```text
//! AudioFeatures (timestamp, beat, section)
//!       ↓  FrameSource::Audio
//! LogicalFrame.provenance
//!       ↓  carried through HAL
//! ProtocolOutput.send_frame(frame)  ← wire bytes
//! ```
//!
//! ## Invariants (lumyx-system-architect)
//! - Every `LogicalFrame` has a `Provenance` — `None` means "generated externally,
//!   no audit trail" (acceptable only in tests and simulator).
//! - `Provenance::timestamp_ms` is always the audio `sample_index`-derived time
//!   — never a wall-clock instant from a non-deterministic source.
//! - `Provenance` is `Clone + Debug + PartialEq` so it can be compared in tests.

/// The originating source of a rendered frame.
#[derive(Clone, Debug, PartialEq)]
pub enum FrameSource {
    /// Frame was rendered in response to live audio analysis.
    Audio {
        /// Timestamp (ms) from the audio pipeline (sample-index derived).
        audio_ts_ms:     u64,
        /// Beat flag at the time of render.
        beat:            bool,
        /// Musical section label at the time of render.
        section:         Option<crate::MusicalSection>,
        /// Instrument class if available.
        instrument:      Option<&'static str>,
    },
    /// Frame was rendered from a static timeline (no live audio).
    Timeline {
        /// Timeline position in ms.
        timeline_ms: u64,
        /// Name of the active effect (debug label).
        effect_name: &'static str,
    },
    /// Frame was generated by the ShowIntent AI composer.
    ShowIntent {
        /// SHA-256 hash of the ShowIntent that produced this frame (hex string).
        intent_hash: u64,
        /// Seed used for deterministic generation.
        seed:        u64,
        /// Frame index within the generated show.
        frame_idx:   u64,
    },
    /// Frame is a heartbeat resend of the last valid frame.
    Heartbeat {
        /// Original frame's timestamp.
        original_ts_ms: u64,
        /// Number of times this frame has been resent.
        resend_count:   u32,
    },
    /// Frame originated from a test or simulator — no production audit trail.
    Simulator,
}

/// Causal chain record attached to every `LogicalFrame`.
#[derive(Clone, Debug, PartialEq)]
pub struct Provenance {
    /// When this frame was produced (ms, sample-index derived — deterministic).
    pub timestamp_ms:   u64,
    /// Pipeline stage that generated the frame.
    pub source:         FrameSource,
    /// FNV-1a hash of the pixel data at render time (for replay verification).
    pub pixel_hash:     u64,
    /// Which crate/module rendered the frame (static string — zero allocation).
    pub renderer:       &'static str,
}

impl Provenance {
    /// Create provenance for a live audio-driven frame.
    pub fn from_audio(
        timestamp_ms: u64,
        beat:         bool,
        section:      Option<crate::MusicalSection>,
        pixel_hash:   u64,
    ) -> Self {
        Self {
            timestamp_ms,
            source: FrameSource::Audio { audio_ts_ms: timestamp_ms, beat, section, instrument: None },
            pixel_hash,
            renderer: "led-pixel-engine",
        }
    }

    /// Create provenance for a timeline-driven frame.
    pub fn from_timeline(timeline_ms: u64, effect_name: &'static str, pixel_hash: u64) -> Self {
        Self {
            timestamp_ms: timeline_ms,
            source: FrameSource::Timeline { timeline_ms, effect_name },
            pixel_hash,
            renderer: "led-sequencer",
        }
    }

    /// Create provenance for a ShowIntent-generated frame.
    pub fn from_show_intent(intent_hash: u64, seed: u64, frame_idx: u64, timestamp_ms: u64, pixel_hash: u64) -> Self {
        Self {
            timestamp_ms,
            source: FrameSource::ShowIntent { intent_hash, seed, frame_idx },
            pixel_hash,
            renderer: "led-show-recorder",
        }
    }

    /// Create provenance for a heartbeat resend.
    pub fn heartbeat(original_ts_ms: u64, resend_count: u32, pixel_hash: u64) -> Self {
        Self {
            timestamp_ms: original_ts_ms,
            source: FrameSource::Heartbeat { original_ts_ms, resend_count },
            pixel_hash,
            renderer: "led-hal",
        }
    }

    /// Provenance for simulator/test frames — no audit trail.
    pub fn simulator(timestamp_ms: u64) -> Self {
        Self {
            timestamp_ms,
            source: FrameSource::Simulator,
            pixel_hash: 0,
            renderer: "simulator",
        }
    }

    /// True if this frame is reproducible from its provenance alone.
    /// (Not true for `Simulator` or `Heartbeat` without the original frame.)
    pub fn is_reproducible(&self) -> bool {
        matches!(
            self.source,
            FrameSource::Audio { .. } | FrameSource::Timeline { .. } | FrameSource::ShowIntent { .. }
        )
    }

    /// Emit a one-line JSON audit record.
    pub fn to_json(&self) -> String {
        let source_type = match &self.source {
            FrameSource::Audio { .. }      => "audio",
            FrameSource::Timeline { .. }   => "timeline",
            FrameSource::ShowIntent { .. } => "show_intent",
            FrameSource::Heartbeat { .. }  => "heartbeat",
            FrameSource::Simulator         => "simulator",
        };
        format!(
            r#"{{"ts":{ts},"source":"{src}","hash":"{hash:#018x}","renderer":"{ren}"}}"#,
            ts   = self.timestamp_ms,
            src  = source_type,
            hash = self.pixel_hash,
            ren  = self.renderer,
        )
    }
}

/// Compute FNV-1a 64-bit hash of pixel data for provenance.
/// Same algorithm as `led-show-recorder::pixel_hash` — one canonical hash function.
pub fn compute_pixel_hash(pixels: &[crate::PixelColor]) -> u64 {
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME:  u64 = 0x00000100000001b3;
    let mut h = FNV_OFFSET;
    for px in pixels {
        h ^= px.r as u64; h = h.wrapping_mul(FNV_PRIME);
        h ^= px.g as u64; h = h.wrapping_mul(FNV_PRIME);
        h ^= px.b as u64; h = h.wrapping_mul(FNV_PRIME);
    }
    h
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{MusicalSection, PixelColor};

    fn px(r: u8, g: u8, b: u8) -> PixelColor { PixelColor::rgb(r, g, b) }

    // ── Construction ──────────────────────────────────────────────────────────

    #[test]
    fn from_audio_sets_correct_source() {
        let p = Provenance::from_audio(1000, true, Some(MusicalSection::Chorus), 0xABCD);
        assert_eq!(p.timestamp_ms, 1000);
        assert!(matches!(p.source, FrameSource::Audio { beat: true, .. }));
        assert_eq!(p.pixel_hash, 0xABCD);
        assert_eq!(p.renderer, "led-pixel-engine");
    }

    #[test]
    fn from_timeline_sets_correct_source() {
        let p = Provenance::from_timeline(500, "Plasma", 0x1234);
        assert!(matches!(p.source, FrameSource::Timeline { effect_name: "Plasma", .. }));
        assert_eq!(p.renderer, "led-sequencer");
    }

    #[test]
    fn from_show_intent_sets_correct_source() {
        let p = Provenance::from_show_intent(0xDEAD, 42, 7, 3000, 0x5678);
        assert!(matches!(p.source, FrameSource::ShowIntent { seed: 42, frame_idx: 7, .. }));
    }

    #[test]
    fn heartbeat_sets_correct_source() {
        let p = Provenance::heartbeat(1000, 3, 0x9999);
        assert!(matches!(p.source, FrameSource::Heartbeat { resend_count: 3, .. }));
    }

    #[test]
    fn simulator_is_not_reproducible() {
        let p = Provenance::simulator(0);
        assert!(!p.is_reproducible());
    }

    #[test]
    fn audio_is_reproducible() {
        let p = Provenance::from_audio(0, false, None, 0);
        assert!(p.is_reproducible());
    }

    #[test]
    fn timeline_is_reproducible() {
        let p = Provenance::from_timeline(0, "test", 0);
        assert!(p.is_reproducible());
    }

    // ── pixel_hash ────────────────────────────────────────────────────────────

    #[test]
    fn pixel_hash_deterministic() {
        let pixels = vec![px(1, 2, 3), px(4, 5, 6)];
        assert_eq!(compute_pixel_hash(&pixels), compute_pixel_hash(&pixels));
    }

    #[test]
    fn pixel_hash_differs_for_different_pixels() {
        let a = vec![px(1, 0, 0)];
        let b = vec![px(0, 1, 0)];
        assert_ne!(compute_pixel_hash(&a), compute_pixel_hash(&b));
    }

    #[test]
    fn pixel_hash_empty_is_fnv_offset() {
        // FNV-1a of empty input = the offset basis
        let h = compute_pixel_hash(&[]);
        assert_eq!(h, 0xcbf29ce484222325u64);
    }

    // ── JSON output ───────────────────────────────────────────────────────────

    #[test]
    fn to_json_contains_required_fields() {
        let p = Provenance::from_audio(1000, true, Some(MusicalSection::Verse), 0xABC);
        let json = p.to_json();
        assert!(json.contains("\"ts\":1000"),       "must include ts");
        assert!(json.contains("\"source\":\"audio\""), "must include source type");
        assert!(json.contains("\"hash\":"),         "must include hash");
        assert!(json.contains("\"renderer\":"),     "must include renderer");
        assert!(json.starts_with('{') && json.ends_with('}'));
    }

    #[test]
    fn to_json_simulator_source_type() {
        let p = Provenance::simulator(42);
        assert!(p.to_json().contains("\"source\":\"simulator\""));
    }

    #[test]
    fn to_json_heartbeat_source_type() {
        let p = Provenance::heartbeat(0, 1, 0);
        assert!(p.to_json().contains("\"source\":\"heartbeat\""));
    }

    // ── Clone + PartialEq ─────────────────────────────────────────────────────

    #[test]
    fn provenance_clone_equals_original() {
        let p = Provenance::from_audio(500, true, Some(MusicalSection::Drop), 0xFFFF);
        assert_eq!(p.clone(), p);
    }

    #[test]
    fn different_timestamps_not_equal() {
        let a = Provenance::simulator(1);
        let b = Provenance::simulator(2);
        assert_ne!(a, b);
    }
}
